version: '3'
services:
  postgres-order:
    image: postgres:latest
    environment:
      POSTGRES_DB: microservice_db_order
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3572
      POSTGRES_PORT: 5432
    command: [ "-p", "5432" ]
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_order:/var/lib/postgresql/data
    networks:
      - app

  postgres-receipt:
    image: postgres:latest
    environment:
      POSTGRES_DB: microservice_db_receipt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3572
      POSTGRES_PORT: 5433 # Порт базы данных внутри контейнера
    command: [ "-p", "5433" ]
    ports:
      - "5433:5433"
    volumes:
      - postgres_data_receipt:/var/lib/postgresql/data
    networks:
      - app

  rabbitmq:
    image: "rabbitmq:management"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app

  app_order:
    build:
      context: .
      dockerfile: ./app_order/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - postgres-order
      - rabbitmq
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
      - app

  app_receipt:
    build:
      context: .
      dockerfile: ./app_receipt/Dockerfile
    ports:
      - "81:81"
    depends_on:
      - postgres-receipt
      - rabbitmq
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
      - app


  pgadmin:
    container_name: pgadmin_docker
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - app

networks:
  app:
  # name: app
volumes:
 postgres_data_order:
 postgres_data_receipt: